#!/usr/bin/env python3
"""Exchangeability-Failure Class (EFC) ranker — session 2026-09-23.

Research-stage classification heuristic. Scores are NOT measurements of nature.
Not a physical discovery, not peer review, not a patent.

Primary operator
----------------
Science treats draws from a calibration generator G_cal as exchangeable with
the unobserved remainder generated by G_target. When G_cal ≠ G_target,
increasing n on G_cal cannot identify G_target (inconsistency, not variance).

This is not:
  undersampling (empty cells of the SAME process),
  TAC (missing converter),
  NCR (named cause insufficient),
  CIC (clock mismatch),
  JAC (unjoined ledgers),
  IOA (missing transfer function),
  PPC (extra hidden DOF),
  TPC (omitted coefficients treated as zero),
  OAC (rank-deficient observable),
  CIP (instrument coupling mismatch),
  CMC (one assigned function treated as filling a channel),
  UPRC (unclosed redox column).

Author: Haley Bird / autonomous Grok research agent
Session: 2026-09-23-efc
"""

from __future__ import annotations

import json
import math
from dataclasses import asdict, dataclass, field
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

OUT = Path("/workspace/artifacts")
OUT.mkdir(parents=True, exist_ok=True)

SESSION_ID = "2026-09-23-efc"
TIMESTAMP = "2026-09-23T14:40:00-04:00"

# Archive classes this session must not reclaim.
PRIOR_CLASSES = [
    ("Dark Biosphere Hypothesis", "2026-05-14"),
    ("Cosmic-Bio Resonance", "2026-05-14"),
    ("Undersampling", "2026-08-03"),
    ("Deep-biosphere-as-space-prior", "2026-08-14"),
    ("Transducer-Absence Class (TAC)", "2026-08-28"),
    ("Cadence Mismatch Class", "2026-08-29"),
    ("Named-Cause Residual (NCR)", "2026-08-30"),
    ("Failed-Adjudication Class (FAC)", "2026-08-31"),
    ("Clock-Incommensurability Class (CIC)", "2026-09-01"),
    ("Join-Absence Class (JAC)", "2026-09-02"),
    ("Interscale-Operator Absence (IOA)", "2026-09-04"),
    ("Destructive-Inquiry Class (DIC)", "2026-09-06"),
    ("Patch-Proliferation Class (PPC)", "2026-09-08"),
    ("Unrecorded-Cessation Class (UCC)", "2026-09-10"),
    ("Discarded-Channel Class (DCC)", "2026-09-12"),
    ("Frontier Coincidence Class (FCC)", "2026-09-13"),
    ("Observable-Aliasing Class (OAC)", "2026-09-14"),
    ("Unclosed Planetary Redox Column (UPRC)", "2026-09-16"),
    ("Coupling Incompleteness Principle (CIP)", "2026-09-17"),
    ("Truncation-Privilege Class (TPC)", "2026-09-20"),
    ("Channel-Monopoly Class (CMC)", "2026-09-20"),
]


@dataclass
class Candidate:
    id: str
    realm: str
    title: str
    g_cal: str
    g_target: str
    more_n_invariance: float  # 1 = more G_cal samples cannot close it
    generator_split: float  # 1 = two generators cleanly identified in sources
    sourcedness: float  # 1 = primary-source locked
    recency: float  # 1 = 2026 evidence floor
    spoken: bool  # famous mystery already in public discourse as THIS claim
    overlap_kind: str  # none | framed_by | reclaim_of
    overlap_class: str
    status: str  # ELIGIBLE | ZEROED | CONTROL
    source: str
    note: str
    framed_tax: float = 0.35
    # filled by scorer
    score: float = 0.0
    verdict: str = ""
    ablation_score: float = 0.0


def validate_unit(name: str, x: float) -> float:
    if not isinstance(x, (int, float)) or isinstance(x, bool):
        raise TypeError(f"{name} must be numeric, got {type(x)}")
    if math.isnan(x) or math.isinf(x):
        raise ValueError(f"{name} not finite: {x}")
    if x < 0.0 or x > 1.0:
        raise ValueError(f"{name} must be in [0, 1], got {x}")
    return float(x)


def efc_score(c: Candidate) -> float:
    """Score an EFC candidate.

    Inputs are unit-interval heuristic weights, not physical measurements.
    Zeroed/control/spoken/reclaim rows return 0.

    Returns a non-negative heuristic. Higher = more remaining EFC surface
    after archive subtraction.
    """
    if c.status in {"ZEROED", "CONTROL"}:
        return 0.0
    if c.spoken:
        return 0.0
    if c.overlap_kind == "reclaim_of":
        return 0.0

    m = validate_unit("more_n_invariance", c.more_n_invariance)
    g = validate_unit("generator_split", c.generator_split)
    s = validate_unit("sourcedness", c.sourcedness)
    r = validate_unit("recency", c.recency)

    tax = 0.0
    if c.overlap_kind == "framed_by":
        tax = validate_unit("framed_tax", c.framed_tax)

    # Product of the four operators, then archive tax.
    raw = (m**1.15) * (g**1.10) * s * (0.55 + 0.45 * r)
    return round(raw * (1.0 - tax) * 100.0, 4)


def more_n_closes(c: Candidate, extra_n_from: str) -> bool:
    """Return True only if adding samples from extra_n_from would identify G_target.

    Edge cases:
      - extra_n_from must be g_cal or g_target
      - reclaim/zeroed rows are not testable as EFC
    """
    if extra_n_from not in {c.g_cal, c.g_target}:
        raise ValueError("extra_n_from must be g_cal or g_target")
    if c.status != "ELIGIBLE":
        return False
    if extra_n_from == c.g_target:
        # Sampling the target generator can close EFC (and may look like
        # undersampling of G_target). That is the discriminator, not the class.
        return True
    # extra_n_from == g_cal
    return c.more_n_invariance < 0.5


def sigma_separation(x: float, mu: float, sigma: float) -> float:
    """Signed separation of a point from a reference mean, in units of sigma.

    Used only as a citation-check for published 3I/ATLAS numbers.
    """
    if sigma <= 0:
        raise ValueError("sigma must be positive")
    return (x - mu) / sigma


CANDIDATES: list[Candidate] = [
    Candidate(
        id="iso-3i-atlas",
        realm="space",
        title="3I/ATLAS isotopic generator ≠ Solar System comet generator",
        g_cal="Solar System comet D/H and 12C/13C (n=thousands of local ices)",
        g_target="Interstellar-object ices (n=3 confirmed ISOs; 1 with JWST isotopes)",
        more_n_invariance=0.97,
        generator_split=0.98,
        sourcedness=0.98,
        recency=0.92,  # Nature 22 Jun 2026; follow-up arXiv 11 Sep 2026
        spoken=False,
        overlap_kind="none",
        overlap_class="",
        status="ELIGIBLE",
        source="Cordiner et al., Nature, 22 Jun 2026, doi:10.1038/s41586-026-10771-6. D/H=(0.98±0.06)%; 15σ above SS comet mean 0.029%. 12C/13C 141–191 (CO2), 123–172 (CO). Formation ≲30 K; possibly ~12 Gyr. Unlike any Solar System body.",
        note="More Solar System comets cannot identify ISO chemistry. 4th ISO is the discriminator, not more local ices.",
    ),
    Candidate(
        id="asgard-oxic",
        realm="life",
        title="Heimdallarchaeia oxic-coastal generator ≠ anoxic-deep Asgard prior",
        g_cal="Anoxic / oxygen-free Asgard samples (the first catalogue)",
        g_target="Oxygen-tolerant Heimdallarchaeia in coastal sediments and water column",
        more_n_invariance=0.90,
        generator_split=0.93,
        sourcedness=0.96,
        recency=0.88,  # Nature 18 Feb 2026
        spoken=False,
        overlap_kind="framed_by",
        overlap_class="Deep-biosphere-as-space-prior / Dark Biosphere (existence of Asgards)",
        status="ELIGIBLE",
        source="Appler et al., Nature 652:405–415, 18 Feb 2026, doi:10.1038/s41586-026-10128-z. 404 Asgard MAGs; 136 new Heimdallarchaeia; aerobic ETC IV, haem biosynthesis, ROS detox. Closest eukaryotic relatives enriched in variably oxygenated coastal sediments.",
        note="Expanding beyond the anoxic generator changed the eukaryogenesis template. Ancestor aerobic respiration still UNPROVED (proposal).",
        framed_tax=0.28,
    ),
    Candidate(
        id="dive-geography",
        realm="ocean",
        title="Deep-sea visual sample is a 3-country EEZ generator, not the ocean",
        g_cal="Dives within 200 nm of US/Japan/NZ (65% of all visual observations)",
        g_target="Global deep seafloor including high seas and non-aligned EEZs",
        more_n_invariance=0.86,
        generator_split=0.84,
        sourcedness=0.95,
        recency=0.80,  # Bell 2025; ODL goals 1 Apr 2026; ODL news 23 Sep 2026
        spoken=False,
        overlap_kind="framed_by",
        overlap_class="Undersampling (WHERE we look)",
        status="ELIGIBLE",
        source="Bell et al., Science Advances 2025: 0.0006–0.001% of deep seafloor seen; 65% of observations within 200 nm of US/Japan/NZ; 97% of dives by 5 countries. ODL Global Deep Sea Exploration Goals, Science Advances 1 Apr 2026: 10,000 stratified sites — a non-random sample, i.e. an admission the filled cells are not exchangeable with the empty ones.",
        note="Undersampling owns empty cells. EFC remainder: the filled cells are a different process (wealthy-nation EEZ, hydrothermal/nodule bias). Random more-n from the same 5 fleets will not identify G_target. Stratified new generators will.",
        framed_tax=0.55,
    ),
    Candidate(
        id="tno-small-end",
        realm="space",
        title="Small TNO generator ≠ large-TNO planet-formation calibration",
        g_cal="Ground-based TNO surveys (larger, brighter bodies)",
        g_target="Webb/Hubble faint TNOs down to ~5 km",
        more_n_invariance=0.78,
        generator_split=0.72,
        sourcedness=0.88,
        recency=0.94,  # NASA 8 Sep 2026
        spoken=False,
        overlap_kind="framed_by",
        overlap_class="Undersampling (faint end)",
        status="ELIGIBLE",
        source="NASA Hubble+Webb, Astronomical Journal, 8 Sep 2026. 27 new dim TNOs; smallest ~5 km; fewer very small bodies than some planet-formation models expected.",
        note="Models trained on the bright end are not exchangeable with the faint generator. Could still be a completeness function (undersampling). Tax accordingly.",
        framed_tax=0.45,
    ),
    Candidate(
        id="shale-fungi",
        realm="land",
        title="Deep-shale fungal generator ≠ surface 'eukaryotes are scarce underground' prior",
        g_cal="Surface / marine-sediment eukaryotic-scarcity prior",
        g_target="Organic-rich shale 247–556 m (fungal:bacterial biomass ~1:4.7)",
        more_n_invariance=0.82,
        generator_split=0.80,
        sourcedness=0.90,
        recency=0.90,  # ISME 24 Aug 2026
        spoken=False,
        overlap_kind="framed_by",
        overlap_class="Dark Biosphere (existence of deep life)",
        status="ELIGIBLE",
        source="ISME Journal, 24 Aug 2026: 4.2e3–6.8e3 fungal cells ml⁻¹ in methane-producing shale; 689 fungal OTUs, 6 phyla; 205 isolates; 13 candidate novel taxa. Median fungal:bacterial biomass 1:4.7 using oceanic conversion factors.",
        note="Dark Biosphere owns 'life is down there.' EFC remainder: the functional template (fungi scarce, bacteria dominate) was a surface generator. Conversion factors themselves may be non-exchangeable — noted, not load-bearing.",
        framed_tax=0.50,
    ),
    Candidate(
        id="hwo-template",
        realm="space",
        title="Earth-photic biosignature templates ≠ exoplanet generating chemistry",
        g_cal="Earth surface photosynthetic O2/CH4/vegetation spectral library",
        g_target="Temperate rocky exoplanet atmospheres (unknown generator)",
        more_n_invariance=0.88,
        generator_split=0.70,
        sourcedness=0.86,
        recency=0.70,  # NASA ExEP Jul 2025; DARES white paper 10 Jan 2026
        spoken=False,
        overlap_kind="framed_by",
        overlap_class="CIP (coupling) / NASA gap list (spoken as false-positive inventory)",
        status="ELIGIBLE",
        source="NASA ExEP Science Gap List, Jul 2025; NASA-DARES 2025 Living Worlds white paper arXiv:2601.06386 (10 Jan 2026): biosignature interpretation requires a false-positive/false-negative framework still incomplete. 3I/ATLAS shows extra-solar chemistry is not Solar-System-like.",
        note="A complete false-positive list built only from Earth photic chemistry is still G_cal. Distinct from CIP (instrument coupling) — this is the prior, not the spectrometer.",
        framed_tax=0.40,
    ),
    Candidate(
        id="ocean-carbon-interface",
        realm="ocean",
        title="Well-sampled gyre carbon generator ≠ land-ocean-ice interface generator",
        g_cal="Open-ocean gyre air-sea flux time series",
        g_target="Coastal, riverine, permafrost, polar ice-driven carbon exchanges",
        more_n_invariance=0.74,
        generator_split=0.68,
        sourcedness=0.90,
        recency=0.85,  # IOC-R 23 Feb 2026
        spoken=False,
        overlap_kind="framed_by",
        overlap_class="Undersampling + JAC (land-ocean continuum)",
        status="ELIGIBLE",
        source="IOC-R Report, IOC/UNESCO, 23 Feb 2026, Ocean Sciences Meeting Glasgow. Ocean absorbs ~25% of anthropogenic CO2; models diverge 10–20% globally, more regionally. Focus area 3: carbon exchanges across the land-ocean-ice continuum.",
        note="More gyre floats will not identify ice/river/coast generators. Tax JAC/undersampling heavily.",
        framed_tax=0.52,
    ),
    Candidate(
        id="human-cry",
        realm="humans",
        title="Bird CRY4 magnetosensitivity ≠ human CRY2 as a sense",
        g_cal="Night-migratory songbird CRY4 / vestibular induction (pigeons)",
        g_target="Human residual magnetosensitivity",
        more_n_invariance=0.70,
        generator_split=0.55,
        sourcedness=0.72,
        recency=0.80,
        spoken=False,
        overlap_kind="framed_by",
        overlap_class="TAC (receptor) / CMC (pigeon vestibular)",
        status="ELIGIBLE",
        source="Conversation 22 Sep 2026: up to six candidate mechanisms; none confirmed as THE receptor. Chae 2025 Frontiers in Neuroscience: RF at 1.26 MHz reproduced a decision effect; author: replication required, not proof. UPRC already: explicitly not demonstrated.",
        note="Bird findings are not exchangeable with humans. Weak generator split; CMC/TAC framing is strong. Keep eligible but expect mid-rank.",
        framed_tax=0.62,
    ),
    # ZEROED / CONTROL
    Candidate(
        id="hubble",
        realm="space",
        title="Hubble tension (local ladder vs CMB)",
        g_cal="Planck/ACT early-universe H0",
        g_target="SH0ES local ladder H0",
        more_n_invariance=0.5,
        generator_split=0.9,
        sourcedness=1.0,
        recency=0.9,
        spoken=True,
        overlap_kind="reclaim_of",
        overlap_class="FAC / CIC two-clock / spoken",
        status="ZEROED",
        source="H0 World Cup II, arXiv:2607.13283, 14 Jul 2026. Nominal >7σ. 14 proposed solutions. Unsettled.",
        note="Two-clock / failed adjudication. Not EFC remainder.",
    ),
    Candidate(
        id="sweetman",
        realm="ocean",
        title="Nodule dark oxygen",
        g_cal="Benthic chamber lander O2 time series",
        g_target="Abiotic seafloor O2 production",
        more_n_invariance=0.4,
        generator_split=0.4,
        sourcedness=0.9,
        recency=0.95,
        spoken=True,
        overlap_kind="reclaim_of",
        overlap_class="FAC / TAC / UPRC do-not-load-bear",
        status="ZEROED",
        source="Sweetman 2024 Nature Geoscience; Downes et al. Front. Mar. Sci. 2025; Science 18 Sep 2026 doubts. Unreplicated. Mechanism unknown or artifact.",
        note="Do not load-bear.",
    ),
    Candidate(
        id="seafloor-n",
        realm="ocean",
        title="Deep seafloor 0.001% visual coverage as an n-problem",
        g_cal="All dives",
        g_target="All deep seafloor",
        more_n_invariance=0.2,
        generator_split=0.3,
        sourcedness=1.0,
        recency=0.8,
        spoken=True,
        overlap_kind="reclaim_of",
        overlap_class="Undersampling",
        status="ZEROED",
        source="Bell et al. 2025. Coverage fraction is a WHERE problem.",
        note="The BIAS of the 0.001% is the EFC row (dive-geography), not the fraction itself.",
    ),
    Candidate(
        id="pigeon-cmc",
        realm="animals",
        title="Pigeon vestibular induction",
        g_cal="Dedicated magnetite-cell search",
        g_target="Semicircular-canal second function",
        more_n_invariance=0.3,
        generator_split=0.5,
        sourcedness=1.0,
        recency=0.7,
        spoken=False,
        overlap_kind="reclaim_of",
        overlap_class="CMC 2026-09-20",
        status="ZEROED",
        source="Nordmann et al., Science, 20 Nov 2025.",
        note="Channel monopoly, not exchangeability.",
    ),
    Candidate(
        id="gorg-ferh",
        realm="ocean",
        title="GORG-Dark FeRh rhodopsins",
        g_cal="Photic rhodopsin coupling",
        g_target="Aphotic FeRh",
        more_n_invariance=0.4,
        generator_split=0.6,
        sourcedness=1.0,
        recency=0.99,
        spoken=False,
        overlap_kind="reclaim_of",
        overlap_class="CIP 2026-09-17",
        status="ZEROED",
        source="GORG-Dark, Cell, 14 Sep 2026.",
        note="Coupling incompleteness. Atlas incompleteness is noted in limitations; not today's primary.",
    ),
    Candidate(
        id="consciousness",
        realm="humans",
        title="Hard problem of consciousness",
        g_cal="Third-person neural correlates",
        g_target="First-person experience",
        more_n_invariance=0.9,
        generator_split=0.8,
        sourcedness=0.9,
        recency=0.7,
        spoken=True,
        overlap_kind="reclaim_of",
        overlap_class="Spoken / FAC Cogitate",
        status="ZEROED",
        source="Scientific American, Jan–Sep 2026; Frontiers 2025.",
        note="Spoken. Zeroed.",
    ),
    Candidate(
        id="larynx",
        realm="humans",
        title="Larynx → speech exaptation (spoken-control)",
        g_cal="Respiratory/digestive larynx",
        g_target="Speech",
        more_n_invariance=0.1,
        generator_split=0.2,
        sourcedness=1.0,
        recency=0.0,
        spoken=True,
        overlap_kind="reclaim_of",
        overlap_class="Gould–Vrba 1982 / CMC control",
        status="CONTROL",
        source="Gould & Vrba 1982. CMC required this to score 0. EFC requires the same: a solved, spoken, old assignment is not a generator split.",
        note="Must score 0. If this ranks, the class is void.",
    ),
    Candidate(
        id="dark-matter",
        realm="space",
        title="Dark-matter particle identity",
        g_cal="WIMP/axion search channels",
        g_target="Whatever sources galactic rotation residuals",
        more_n_invariance=0.5,
        generator_split=0.4,
        sourcedness=1.0,
        recency=0.8,
        spoken=True,
        overlap_kind="reclaim_of",
        overlap_class="TAC / CIP / spoken",
        status="ZEROED",
        source="LZ 2.6σ is not a discovery (DOE 1 Sep 2026). Clini et al. arXiv:2609.17423 ~2.5–3σ EP in dark sector — CIP slot.",
        note="Spoken identity gap. Zeroed.",
    ),
]


def rank(cands: list[Candidate], recency_ablation: bool = False) -> list[Candidate]:
    out = []
    for c in cands:
        c2 = Candidate(**{k: getattr(c, k) for k in c.__dataclass_fields__})
        if recency_ablation:
            c2.recency = 0.5  # flatten recency so a 2026 scoop cannot buy the class
        c2.score = efc_score(c2)
        if recency_ablation:
            c2.ablation_score = c2.score
        if c2.status == "CONTROL":
            c2.verdict = "CONTROL — must stay 0 or class is void"
        elif c2.status == "ZEROED" or c2.score == 0:
            c2.verdict = f"ZEROED ({c2.overlap_class or 'spoken/reclaim'})"
        elif c2.overlap_kind == "framed_by":
            c2.verdict = f"ELIGIBLE remainder after {c2.overlap_class}"
        else:
            c2.verdict = "ELIGIBLE — no archive overlap"
        out.append(c2)
    out.sort(key=lambda x: (-x.score, x.id))
    return out


def spearman(xs: list[float], ys: list[float]) -> float:
    """Spearman rho without scipy. Ties get average ranks."""
    if len(xs) != len(ys) or len(xs) < 3:
        raise ValueError("need >=3 paired observations")

    def ranks(a: list[float]) -> list[float]:
        n = len(a)
        order = sorted(range(n), key=lambda i: a[i])
        r = [0.0] * n
        i = 0
        while i < n:
            j = i
            while j + 1 < n and a[order[j + 1]] == a[order[i]]:
                j += 1
            avg = (i + j) / 2.0 + 1.0
            for k in range(i, j + 1):
                r[order[k]] = avg
            i = j + 1
        return r

    rx, ry = ranks(xs), ranks(ys)
    mx, my = sum(rx) / len(rx), sum(ry) / len(ry)
    num = sum((a - mx) * (b - my) for a, b in zip(rx, ry))
    denx = math.sqrt(sum((a - mx) ** 2 for a in rx))
    deny = math.sqrt(sum((b - my) ** 2 for b in ry))
    if denx == 0 or deny == 0:
        return 0.0
    return num / (denx * deny)


def iterate_after_adversary(ranked: list[Candidate]) -> dict[str, Any]:
    """Adversarial pass.

    Attack 1: 3I/ATLAS is just undersampling of ISOs (n=3).
    Attack 2: Asgard is just Dark Biosphere.
    Attack 3: Dive geography is just undersampling.
    Attack 4: Recency bought the leader.
    Attack 5: Larynx control escaped zero.
    """
    notes = []
    leader = next((c for c in ranked if c.score > 0), None)

    # Attack 1
    iso = next(c for c in ranked if c.id == "iso-3i-atlas")
    if more_n_closes(iso, iso.g_cal):
        notes.append("FAIL Attack1: more Solar System comets would close 3I gap — then it is not EFC.")
    else:
        notes.append(
            "SURVIVE Attack1: more_n_closes(G_cal)=False. Undersampling of ISOs is real and is the discriminator (4th ISO). EFC remainder is template-lock of G_cal. Cordiner 15σ vs SS mean is a generator split, not an empty cell."
        )

    # Attack 2
    asg = next(c for c in ranked if c.id == "asgard-oxic")
    if asg.overlap_kind != "framed_by":
        notes.append("FAIL Attack2: Asgard not taxed for Dark Biosphere overlap.")
    else:
        notes.append(
            "SURVIVE Attack2: existence of Asgards is prior IP. Remainder is that the anoxic catalogue was the wrong generator; expanding generators changed the eukaryogenesis template. Ancestor-was-aerobic remains UNPROVED."
        )

    # Attack 3
    dive = next(c for c in ranked if c.id == "dive-geography")
    if dive.framed_tax < 0.4:
        notes.append("FAIL Attack3: dive geography under-taxed vs undersampling.")
    else:
        notes.append(
            "SURVIVE Attack3: coverage fraction zeroed as undersampling. Remainder is non-exchangeability of the filled cells (3-country EEZ generator). ODL's stratified 10,000-site plan is a tacit EFC admission."
        )

    # Attack 4 recency ablation
    ablated = rank(CANDIDATES, recency_ablation=True)
    ab_leader = next((c for c in ablated if c.score > 0), None)
    if leader and ab_leader and leader.id == ab_leader.id:
        notes.append(f"SURVIVE Attack4: recency ablation leaves leader={leader.id}.")
    else:
        notes.append(
            f"NOTE Attack4: ablation leader={ab_leader.id if ab_leader else None} vs base={leader.id if leader else None}."
        )

    # Attack 5 control
    larynx = next(c for c in ranked if c.id == "larynx")
    if larynx.score != 0:
        notes.append("FAIL Attack5: larynx control scored >0. CLASS VOID.")
    else:
        notes.append("SURVIVE Attack5: larynx control = 0.")

    # Published 15σ check (citation lock, not a discovery)
    dh_3i, dh_ss, sigma_ss = 0.0098, 0.00029, None
    # Paper: 15σ above mean 0.029% using combined std of the SS sample, not the 3I error bar.
    # We do not recompute σ_SS (not published as a single number here). Lock the paper's 15σ.
    notes.append(
        "CITATION LOCK: Cordiner reports D/H=(0.98±0.06)% = 15σ above SS comet mean 0.029%. This engine does not re-derive σ_SS. Do not quote a homemade sigma."
    )

    eligible = [c for c in ranked if c.score > 0]
    if len(eligible) >= 3:
        rho = spearman(
            [c.more_n_invariance for c in eligible],
            [c.score for c in eligible],
        )
    else:
        rho = None

    return {
        "leader": leader.id if leader else None,
        "leader_score": leader.score if leader else 0,
        "ablation_leader": ab_leader.id if ab_leader else None,
        "ablation_leader_score": ab_leader.score if ab_leader else 0,
        "larynx_score": larynx.score,
        "class_void": larynx.score != 0,
        "spearman_more_n_vs_score": rho,
        "n_eligible": len(eligible),
        "n_zeroed": sum(1 for c in ranked if c.score == 0),
        "notes": notes,
        "ablation_ranking": [
            {"id": c.id, "score": c.score, "realm": c.realm} for c in ablated if c.score > 0
        ],
    }


def plot_ranking(ranked: list[Candidate], path: Path) -> None:
    import matplotlib.pyplot as plt

    rows = [c for c in ranked if c.status == "ELIGIBLE"]
    rows = sorted(rows, key=lambda c: c.score)
    colors = {
        "space": "#7dd3fc",
        "ocean": "#38bdf8",
        "life": "#86efac",
        "land": "#fbbf24",
        "humans": "#f9a8d4",
        "animals": "#c4b5fd",
        "earth": "#fdba74",
    }
    fig, ax = plt.subplots(figsize=(11, 6.2), dpi=160)
    fig.patch.set_facecolor("#0b1220")
    ax.set_facecolor("#0b1220")
    y = range(len(rows))
    ax.barh(
        list(y),
        [c.score for c in rows],
        color=[colors.get(c.realm, "#94a3b8") for c in rows],
        edgecolor="#1e293b",
        height=0.72,
    )
    labels = [f"{c.realm} · {c.title[:54]}" for c in rows]
    ax.set_yticks(list(y), labels, color="#e2e8f0", fontsize=8)
    ax.set_xlabel("EFC heuristic score (not a measurement of nature)", color="#94a3b8", fontsize=9)
    ax.tick_params(colors="#94a3b8")
    for spine in ax.spines.values():
        spine.set_color("#1e293b")
    ax.set_title(
        "Exchangeability-Failure Class — remaining surface after archive subtraction\n"
        "2026-09-23  ·  scores are a classification heuristic",
        color="#f8fafc",
        fontsize=11,
        loc="left",
        pad=12,
    )
    ax.grid(axis="x", color="#1e293b", linewidth=0.6)
    fig.tight_layout()
    fig.savefig(path, facecolor=fig.get_facecolor())
    plt.close()


def main() -> None:
    ranked = rank(CANDIDATES)
    adv = iterate_after_adversary(ranked)

    payload = {
        "session_id": SESSION_ID,
        "timestamp": TIMESTAMP,
        "class": "Exchangeability-Failure Class (EFC)",
        "primary_insight": (
            "Science treats the calibration sample as exchangeable with the unobserved remainder. "
            "When the remainder is generated by a different process, more n on the calibration "
            "generator cannot identify the target. The 22 Jun 2026 Nature isotopes of 3I/ATLAS "
            "(D/H 15σ above Solar System comets) are the cleanest generator split in the 2026 "
            "record that no prior archive class owns."
        ),
        "prior_classes": [{"name": n, "date": d} for n, d in PRIOR_CLASSES],
        "adversarial": adv,
        "ranking": [
            {
                "rank": i + 1,
                "score": c.score,
                "id": c.id,
                "realm": c.realm,
                "title": c.title,
                "g_cal": c.g_cal,
                "g_target": c.g_target,
                "verdict": c.verdict,
                "status": c.status,
                "overlap_kind": c.overlap_kind,
                "overlap_class": c.overlap_class,
                "source": c.source,
                "note": c.note,
                "more_n_closes_g_cal": more_n_closes(c, c.g_cal) if c.status == "ELIGIBLE" else None,
                "more_n_closes_g_target": more_n_closes(c, c.g_target) if c.status == "ELIGIBLE" else None,
            }
            for i, c in enumerate(ranked)
        ],
    }

    json_path = OUT / "efc_ranking.json"
    json_path.write_text(json.dumps(payload, indent=2), encoding="utf-8")

    lines = [
        f"EFC ranking  {TIMESTAMP}  {SESSION_ID}",
        f"Leader: {adv['leader']}  score={adv['leader_score']}",
        f"Ablation leader: {adv['ablation_leader']}  score={adv['ablation_leader_score']}",
        f"Class void: {adv['class_void']}  larynx={adv['larynx_score']}",
        f"Spearman(more_n_invariance, score) among eligible: {adv['spearman_more_n_vs_score']}",
        "",
        f"{'rk':>3} {'score':>8} {'realm':<8} {'id':<22} verdict",
        "-" * 108,
    ]
    for i, c in enumerate(ranked, 1):
        lines.append(f"{i:3d} {c.score:8.3f} {c.realm:<8} {c.id:<22} {c.verdict}")
    lines.append("")
    lines.extend(adv["notes"])
    txt_path = OUT / "efc_ranking.txt"
    txt_path.write_text("\n".join(lines) + "\n", encoding="utf-8")

    plot_ranking(ranked, OUT / "efc_ranking.png")

    print("\n".join(lines))
    print(f"\nWrote {json_path}")
    print(f"Wrote {txt_path}")
    print(f"Wrote {OUT / 'efc_ranking.png'}")


if __name__ == "__main__":
    main()
